name: "CI: Quality + Security"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write   # Required for OIDC token
  contents: read

jobs:
  build_and_scan:
    name: Build, SonarQube & Trivy Scans
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & run tests
        run: |
          npm install
          npm test
        working-directory: ./backend

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        timeout-minutes: 5

      - name: Trivy FS Scan
        run: trivy fs --severity HIGH,CRITICAL --exit-code 1 .
        working-directory: ./backend
